//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCInternationalSchool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OAF_DBEntities : DbContext
    {
        public OAF_DBEntities()
            : base("name=OAF_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Report> Reports { get; set; }
        public DbSet<Seat> Seats { get; set; }
        public DbSet<Processed_applications> Processed_applications { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Branch> Branches { get; set; }
    }
}
