//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCInternationalSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processed_applications
    {
        public int App_id { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Date_of_Resolve { get; set; }
        public string ResolvedBy { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
